import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

const LANGUAGES = {
    en: { label: 'English', nativeName: 'English', flag: '🇺🇸' },
    bn: { label: 'বাংলা', nativeName: 'Bengali', flag: '🇧🇩' },
    hi: { label: 'हिन्दी', nativeName: 'Hindi', flag: '🇮🇳' },
    ar: { label: 'العربية', nativeName: 'Arabic', flag: '🇸🇦' },
};

const translations = {
    en: {
        welcome: 'Welcome!',
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        settings: 'Settings',
        profile: 'Profile',
        editProfile: 'Edit Profile',
        addresses: 'Addresses',
        password: 'Password',
        notifications: 'Notifications',
        overview: 'Overview',
        quickAccess: 'Quick Access',
        preferences: 'Preferences',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        notificationSettings: 'Notification Settings',
        adminPanel: 'Admin Panel',
        manageProducts: 'Manage products',
        fullName: 'Full Name',
        email: 'Email',
        phone: 'Phone',
        bio: 'Bio',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        savedAddresses: 'Saved Addresses',
        addNew: '+ New',
        addressLabel: 'Label (Home/Office)',
        recipientName: 'Recipient Name',
        fullAddress: 'Full Address',
        makeDefault: 'Make Default',
        default: 'Default',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        showPassword: 'Show Password',
        orderUpdates: 'Order Updates',
        orderUpdatesDesc: 'Get notified when your order status changes',
        promotions: 'Promotions & Offers',
        promotionsDesc: 'Learn about new discounts and deals',
        newArrivals: 'New Arrivals',
        newArrivalsDesc: 'Get notified about new products',
        priceDrops: 'Price Drops',
        priceDropsDesc: 'Get notified when wishlist items drop in price',
        wishlist: 'Wishlist',
        orders: 'Orders',
        recentlyViewed: 'Recently Viewed',
        compare: 'Compare',
        myCart: 'My Cart',
        items: 'items',
        cartEmpty: 'Your cart is empty',
        addFromHome: 'Add products from the home page',
        shopNow: 'Shop Now',
        orderSummary: 'Order Summary',
        subtotal: 'Subtotal',
        deliveryCharge: 'Delivery Charge',
        discount: 'Discount',
        total: 'Total',
        goToCheckout: 'Go to Checkout',
        youMayAlsoLike: 'You may also like',
        checkout: 'Checkout',
        guestCheckout: 'Guest Checkout',
        completeOrder: 'Complete your order',
        contact: 'Contact',
        shipping: 'Shipping',
        payment: 'Payment',
        review: 'Review',
        contactInfo: 'Contact Information',
        shippingAddress: 'Shipping Address',
        paymentMethod: 'Payment Method',
        address: 'Address',
        city: 'City',
        area: 'Area',
        postcode: 'Postcode',
        country: 'Country',
        billingSameAsShipping: 'Billing address same as shipping',
        billingAddress: 'Billing Address',
        orderNote: 'Order Note (optional)',
        deliveryInstructions: 'Delivery instructions',
        cod: 'Cash on Delivery',
        cardPayment: 'Card Payment',
        giftWrap: 'Gift Wrap',
        giftMessage: 'Write a gift message...',
        saveInfoForLater: 'Save info for next time',
        nextShipping: 'Next: Shipping Address →',
        nextPayment: 'Next: Payment →',
        nextReview: 'Next: Review →',
        previous: '← Previous',
        change: 'Change',
        confirmOrder: 'Confirm Order',
        ordering: 'Ordering...',
        loginToTrack: 'Login to track your orders',
        categories: 'Categories',
        findProducts: 'Find products across categories',
        products: 'Products',
        noProductsInCategory: 'No products in this category',
        viewAllCategories: 'View All Categories',
        defaultSort: 'Default',
        lowPrice: 'Low Price',
        highPrice: 'High Price',
        topRating: 'Top Rating',
        flashSale: 'Flash Sale',
        todaysSpecial: "Today's special offers — limited time!",
        endsIn: 'Ends in',
        later: 'later',
        bestDiscount: 'Best Discount',
        endingSoon: 'Ending Soon',
        noFlashSale: 'No flash sale products',
        goHome: 'Go Home',
        sold: 'sold',
        addedToCart: '✓ Added',
        addToCart: 'Add to Cart',
        outOfStock: 'Out of Stock',
        onlyLeft: 'Only left!',
        savedProducts: 'Saved products',
        itemsSaved: 'items saved',
        noSavedProducts: 'No saved products yet',
        tapHeart: 'Tap the heart on any product to save it here.',
        myOrders: 'My Orders',
        yourOrdersHere: 'Your confirmed orders appear here.',
        orderHistoryLogin: 'Order history is available after login.',
        loginRequired: 'Login Required',
        signInOrders: 'Sign in to view your order history',
        noOrdersYet: 'No orders yet',
        placeFirstOrder: 'Place your first order',
        addToCartCheckout: 'Add products to cart and place an order from checkout.',
        trackOrder: 'Track order',
        cancelOrder: 'Cancel Order',
        cancelling: 'Cancelling...',
        productFinder: 'Product Finder',
        resultsFor: 'Results for',
        browseAll: 'Browse all products',
        filterByCategory: 'Filter by category and sort by price or rating.',
        showFilters: 'Show Filters',
        hideFilters: 'Hide Filters',
        advancedFilters: 'Advanced Filters',
        priceRange: 'Price Range',
        minimumRating: 'Minimum Rating',
        inStockOnly: 'In Stock Only',
        resetFilters: 'Reset Filters',
        sortBy: 'Sort by',
        noProductsFound: 'No products found',
        tryAnotherKeyword: 'Try another keyword or browse categories.',
        browseCategories: 'Browse Categories',
        found: 'found',
        browsingHistory: 'Browsing History',
        noRecentlyViewed: 'No recently viewed products',
        productsWillAppear: 'Products you view will appear here.',
        browseProducts: 'Browse Products',
        clear: 'Clear',
        inStock: 'In Stock',
        onlyXLeft: 'Only {x} left!',
        deliveryInfo: 'Delivery Information',
        deliveryDhaka: 'Delivery in Dhaka: 1-2 days',
        deliveryOutside: 'Outside Dhaka: 3-5 days',
        cashOnDelivery: 'Cash on Delivery',
        returnPolicy: '7-day Return Policy',
        soldCount: '{x}+ sold',
        phoneOrEmail: 'Phone / Email',
        yourPassword: 'Your password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot Password?',
        loggingIn: 'Logging in...',
        or: 'or',
        loginWithGoogle: 'Login with Google',
        loginWithFacebook: 'Login with Facebook',
        noAccount: "Don't have an account?",
        createAccount: 'Create Account',
        startShopping: 'Start shopping on Progotix',
        yourFullName: 'Your full name',
        phoneNumber: 'Phone Number',
        minChars: 'Minimum 6 characters',
        confirmPassword: 'Confirm Password',
        reenterPassword: 'Re-enter password',
        agreeToTerms: "I agree to Progotix's",
        termsConditions: 'Terms & Conditions',
        and: 'and',
        privacyPolicy: 'Privacy Policy',
        registering: 'Registering...',
        signupWithGoogle: 'Sign up with Google',
        signupWithFacebook: 'Sign up with Facebook',
        haveAccount: 'Already have an account?',
        language: 'Language',
        currency: 'Currency',
        guestShopper: 'Guest Shopper',
        loginToStart: 'Login to start shopping',
        bestMatch: 'Best Match',
        itemsFound: 'items found',
    },
    bn: {
        welcome: 'স্বাগতম!',
        login: 'লগইন',
        register: 'রেজিস্টার',
        logout: 'লগআউট',
        settings: 'সেটিংস',
        profile: 'প্রোফাইল',
        editProfile: 'প্রোফাইল সম্পাদনা',
        addresses: 'ঠিকানা',
        password: 'পাসওয়ার্ড',
        notifications: 'নোটিফিকেশন',
        overview: 'ওভারভিউ',
        quickAccess: 'দ্রুত প্রবেশ',
        preferences: 'পছন্দ',
        darkMode: 'ডার্ক মোড',
        lightMode: 'লাইট মোড',
        notificationSettings: 'নোটিফিকেশন সেটিংস',
        adminPanel: 'এডমিন প্যানেল',
        manageProducts: 'পণ্য ম্যানেজ করুন',
        fullName: 'পুরো নাম',
        email: 'ইমেইল',
        phone: 'ফোন',
        bio: 'বায়ো',
        save: 'সেভ করুন',
        cancel: 'বাতিল',
        delete: 'মুছুন',
        savedAddresses: 'সেভ করা ঠিকানা',
        addNew: '+ নতুন',
        addressLabel: 'লেবেল (বাসা/অফিস)',
        recipientName: 'প্রাপকের নাম',
        fullAddress: 'পুরো ঠিকানা',
        makeDefault: 'ডিফল্ট করুন',
        default: 'ডিফল্ট',
        changePassword: 'পাসওয়ার্ড পরিবর্তন',
        currentPassword: 'বর্তমান পাসওয়ার্ড',
        newPassword: 'নতুন পাসওয়ার্ড',
        confirmNewPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
        showPassword: 'পাসওয়ার্ড দেখুন',
        orderUpdates: 'অর্ডার আপডেট',
        orderUpdatesDesc: 'অর্ডারের স্ট্যাটাস পরিবর্তনের নোটিফিকেশন',
        promotions: 'প্রমোশন ও অফার',
        promotionsDesc: 'নতুন ডিস্কাউন্ট ও ডিল সম্পর্কে জানুন',
        newArrivals: 'নতুন পণ্য',
        newArrivalsDesc: 'নতুন পণ্য আসলে জানুন',
        priceDrops: 'মূল্য হ্রাস',
        priceDropsDesc: 'উইশলিস্টের পণ্যের দাম কমলে জানুন',
        wishlist: 'উইশলিস্ট',
        orders: 'অর্ডার',
        recentlyViewed: 'সম্প্রতি দেখা',
        compare: 'তুলনা করুন',
        myCart: 'আমার কার্ট',
        items: 'পণ্য',
        cartEmpty: 'আপনার কার্ট খালি',
        addFromHome: 'হোম পেজ থেকে পণ্য যোগ করুন',
        shopNow: 'শপিং করুন',
        orderSummary: 'অর্ডার সারাংশ',
        subtotal: 'সাবটোটাল',
        deliveryCharge: 'ডেলিভারি চার্জ',
        discount: 'ডিসকাউন্ট',
        total: 'মোট',
        goToCheckout: 'চেকআউটে যান',
        youMayAlsoLike: 'আপনি পছন্দ করতে পারেন',
        checkout: 'চেকআউট',
        guestCheckout: 'গেস্ট চেকআউট',
        completeOrder: 'আপনার অর্ডার সম্পন্ন করুন',
        contact: 'যোগাযোগ',
        shipping: 'শিপিং',
        payment: 'পেমেন্ট',
        review: 'রিভিউ',
        contactInfo: 'যোগাযোগ তথ্য',
        shippingAddress: 'শিপিং ঠিকানা',
        paymentMethod: 'পেমেন্ট মেথড',
        address: 'ঠিকানা',
        city: 'শহর',
        area: 'এলাকা',
        postcode: 'পোস্টকোড',
        country: 'দেশ',
        billingSameAsShipping: 'বিলিং ঠিকানা শিপিং-এর মতো',
        billingAddress: 'বিলিং ঠিকানা',
        orderNote: 'অর্ডার নোট (ঐচ্ছিক)',
        deliveryInstructions: 'ডেলিভারি নির্দেশনা',
        cod: 'ক্যাশ অন ডেলিভারি',
        cardPayment: 'কার্ড পেমেন্ট',
        giftWrap: 'গিফট র‍্যাপ',
        giftMessage: 'গিফট মেসেজ লিখুন...',
        saveInfoForLater: 'পরবর্তী সময়ের জন্য তথ্য সংরক্ষণ করুন',
        nextShipping: 'পরবর্তী: শিপিং ঠিকানা →',
        nextPayment: 'পরবর্তী: পেমেন্ট →',
        nextReview: 'পরবর্তী: রিভিউ →',
        previous: '← আগের',
        change: 'পরিবর্তন',
        confirmOrder: 'অর্ডার কনফার্ম করুন',
        ordering: 'অর্ডার হচ্ছে...',
        loginToTrack: 'লগইন করলে অর্ডার ট্র্যাক করতে পারবেন',
        categories: 'ক্যাটাগরি',
        findProducts: 'ক্যাটাগরিতে পণ্য খুঁজুন',
        products: 'পণ্য',
        noProductsInCategory: 'এই ক্যাটাগরিতে পণ্য নেই',
        viewAllCategories: 'সব ক্যাটাগরি দেখুন',
        defaultSort: 'ডিফল্ট',
        lowPrice: 'কম দাম',
        highPrice: 'বেশি দাম',
        topRating: 'সেরা রেটিং',
        flashSale: 'ফ্ল্যাশ সেল',
        todaysSpecial: 'আজকের বিশেষ অফার — সীমিত সময়!',
        endsIn: 'শেষ হবে',
        later: 'পরে',
        bestDiscount: 'সেরা ডিস্কাউন্ট',
        endingSoon: 'শেষ হচ্ছে',
        noFlashSale: 'ফ্ল্যাশ সেলে পণ্য নেই',
        goHome: 'হোমে যান',
        sold: 'বিক্রি',
        addedToCart: '✓ যোগ হয়েছে',
        addToCart: 'কার্টে যোগ করুন',
        outOfStock: 'স্টক শেষ',
        onlyLeft: 'মাত্র বাকি!',
        savedProducts: 'সেভ করা পণ্য',
        itemsSaved: 'পণ্য সেভ করা আছে',
        noSavedProducts: 'এখনো কোনো পণ্য সেভ করেননি',
        tapHeart: 'যেকোনো পণ্যে হার্ট চাপুন সেভ করতে',
        myOrders: 'আমার অর্ডার',
        yourOrdersHere: 'আপনার অর্ডারসমূহ এখানে দেখুন',
        orderHistoryLogin: 'অর্ডার হিস্টোরি দেখতে লগইন করুন',
        loginRequired: 'লগইন প্রয়োজন',
        signInOrders: 'অর্ডার হিস্টোরি দেখতে লগইন করুন',
        noOrdersYet: 'এখনো কোনো অর্ডার নেই',
        placeFirstOrder: 'প্রথম অর্ডার করুন',
        addToCartCheckout: 'কার্টে পণ্য যোগ করে চেকআউট থেকে অর্ডার করুন',
        trackOrder: 'ট্র্যাক করুন',
        cancelOrder: 'অর্ডার বাতিল',
        cancelling: 'বাতিল হচ্ছে...',
        productFinder: 'পণ্য খুঁজুন',
        resultsFor: 'এর ফলাফল',
        browseAll: 'সব পণ্য ব্রাউজ করুন',
        filterByCategory: 'ক্যাটাগরি ও দাম অনুযায়ী ফিল্টার করুন',
        showFilters: 'ফিল্টার দেখুন',
        hideFilters: 'ফিল্টার লুকান',
        advancedFilters: 'আডভান্সড ফিল্টার',
        priceRange: 'মূল্যের পরিসর',
        minimumRating: 'ন্যূনতম রেটিং',
        inStockOnly: 'শুধু স্টকে আছে',
        resetFilters: 'ফিল্টার রিসেট',
        sortBy: 'সাজান',
        noProductsFound: 'কোনো পণ্য পাওয়া যায়নি',
        tryAnotherKeyword: 'অন্য কীওয়ার্ড দিয়ে খুঁজুন বা ক্যাটাগরি দেখুন',
        browseCategories: 'ক্যাটাগরি দেখুন',
        found: 'পাওয়া গেছে',
        browsingHistory: 'ব্রাউজিং হিস্টোরি',
        noRecentlyViewed: 'এখনো কোনো পণ্য দেখেননি',
        productsWillAppear: 'যেসব পণ্য দেখবেন সেগুলো এখানে দেখা যাবে',
        browseProducts: 'পণ্য দেখুন',
        clear: 'মুছুন',
        inStock: 'স্টকে আছে',
        deliveryInfo: 'ডেলিভারি তথ্য',
        deliveryDhaka: 'ঢাকায় ১-২ দিনে ডেলিভারি',
        deliveryOutside: 'ঢাকার বাইরে ৩-৫ দিন',
        cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
        returnPolicy: '৭ দিনে রিটার্ন পলিসি',
        phoneOrEmail: 'ফোন নম্বর / ইমেইল',
        yourPassword: 'আপনার পাসওয়ার্ড',
        rememberMe: 'মনে রাখুন',
        forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
        loggingIn: 'লগইন হচ্ছে...',
        or: 'অথবা',
        loginWithGoogle: 'Google দিয়ে লগইন',
        loginWithFacebook: 'Facebook দিয়ে লগইন',
        noAccount: 'একাউন্ট নেই?',
        createAccount: 'একাউন্ট তৈরি করুন',
        startShopping: 'Progotix-এ শপিং শুরু করুন',
        yourFullName: 'আপনার পুরো নাম',
        phoneNumber: 'ফোন নম্বর',
        minChars: 'কমপক্ষে ৬ অক্ষর',
        confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
        reenterPassword: 'আবার পাসওয়ার্ড দিন',
        agreeToTerms: 'আমি Progotix-এর',
        termsConditions: 'শর্তাবলী',
        and: 'ও',
        privacyPolicy: 'গোপনীয়তা নীতি',
        registering: 'রেজিস্টার হচ্ছে...',
        signupWithGoogle: 'Google দিয়ে সাইন আপ',
        signupWithFacebook: 'Facebook দিয়ে সাইন আপ',
        haveAccount: 'একাউন্ট আছে?',
        language: 'ভাষা',
        currency: 'মুদ্রা',
        guestShopper: 'গেস্ট শপার',
        loginToStart: 'লগইন করে শপিং শুরু করুন',
        bestMatch: 'সেরা ম্যাচ',
        itemsFound: 'পণ্য পাওয়া গেছে',
    },
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('progotix_language') || 'en';
        }
        return 'en';
    });

    const changeLanguage = useCallback((lang) => {
        setLanguage(lang);
        if (typeof window !== 'undefined') {
            localStorage.setItem('progotix_language', lang);
        }
    }, []);

    const t = useCallback((key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    }, [language]);

    return (
        <LanguageContext.Provider
            value={{
                language,
                changeLanguage,
                t,
                availableLanguages: LANGUAGES,
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
